### ISSUE TITLE
inconsistency in declaration of cue_scanner_free in cue_parser.y

### ISSUE THREAD

**Issue by rhash** [libyal/libodraw#10]
Hello,

here is the patch for the Debian [Bug #749000](http://bugs.debian.org/749000):

[0001-Fix-wrong-return-value-of-the-cue_scanner_free-funct.patch.gz](https://github.com/libyal/libodraw/files/2770703/0001-Fix-wrong-return-value-of-the-cue_scanner_free-funct.patch.gz)

The patch fixes wrong return value of the cue_scanner_free() function.  The cue_scanner_free() function has void return value, but it is incorrectly declared as void*.

**Comment by joachimmetz** [comment]
Thx, I'll integrate these patches in the next update.

**Comment by joachimmetz** [comment]
Change integrated in https://github.com/libyal/libodraw/commit/e8cb77785d14d98c740d34452cdfe98d99fb9517, closing issue
