### ISSUE TITLE
byacc syntax error

### ISSUE THREAD

**Issue by VernMcC** [libyal/libodraw#3]
When trying to make libewf, the process errors when making all in libodraw.  The error is in libodraw_cue_parser.y at line 75

byacc: e - line 75 of "/home/student/cyb652/week1/libewf/libodraw/libodraw_cue_parser.y", syntax error
%lex-param { NULL }
                                ^

When I commented out this line (line 75 of libodraw_cue_parser.y) , the make worked as usual.  I noted that you added the line on 1/25.  I don't know why this is a syntax error yet, but wanted to report it even though I got libewf to compile.

**Comment by VernMcC** [comment]
That ^ character was under the right most (closing) brace.

**Comment by joachimmetz** [comment]
I'll have a look the line was added for winflexbison support and should be supported by [bison[(http://www.gnu.org/software/bison/manual/html_node/Pure-Calling.html). Not sure why byacc is not supporting it.

**Comment by joachimmetz** [comment]
https://github.com/libyal/libodraw/commit/c7da8a1ac1467a0736c0e0dc337681436b066d0a
